# Generated by Django 4.2.4 on 2023-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': '이미 사용중인 이메일 이거나 탈퇴한 이메일입니다.'}, max_length=255, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 야부')),
                ('is_active', models.BooleanField(default=True, verbose_name='로그인 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='계정 수정일')),
            ],
            options={
                'db_table': 'ACCOUNT',
            },
        ),
    ]
